/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package server;

import function.Function;
import java.awt.CardLayout;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStreamReader;
import java.sql.SQLException;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.SwingUtilities;


/**
 *
 * @author gauthier
 */
public class InterfaceServer extends javax.swing.JFrame {
	private static final long serialVersionUID =1L;
	private Server server;
	private Bdd bdd;
	private CardLayout view;

	private String tag =Function.color(this);


	/**
	 * Creates new form Interface
	 */
	public InterfaceServer() {
		initComponents();

		this.setTitle("server application");
		this.setSize(1600, 900);
		this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		this.setLocationRelativeTo(null);
		this.setResizable(false);
		this.setVisible(true);
//		this.pack();

		new Thread() {
			@Override
			public void run() {
				bddConnect();
				temporize();
				temporize();
				temporize();
				serverConnect();
				temporize();
			}
		}.start();

//
//		try {
//			Thread.sleep(1000);
//		} catch (InterruptedException ex) {
//			Logger.getLogger(InterfaceServer.class.getName()).log(Level.SEVERE, null, ex);
//		}
//
//
//		server.waitClient();
		
//
//		try {
//			Thread.sleep(delay);
//		} catch (InterruptedException ex) {
//			Logger.getLogger(InterfaceServer.class.getName()).log(Level.SEVERE, null, ex);
//		}
//		jLabel11.setVisible(false);
////		jLabel7.setVisible(true);
//		if (bddFailed) {
//			home_view_bdd.setBackground(Color.red);
//			return;
//		}
//		else
//			home_view_bdd.setBackground(Color.green);
//
//		jTextField1.setText(bdd.uniq("select version()"));
//
//
//		jLabel15.setVisible(true);
//		server = new Server(5000, 100, bdd, this);
//
//		try {
//			Thread.sleep(delay);
//		} catch (InterruptedException ex) {
//			Logger.getLogger(InterfaceServer.class.getName()).log(Level.SEVERE, null, ex);
//		}
//
//		jLabel15.setVisible(false);
////		jLabel14.setVisible(true);
//		if (server.openingCommunication()) {
//			home_view_server.setBackground(Color.green);
//		} 
//		else {
//			home_view_server.setBackground(Color.red);
//			return;
//		}
//
//		String output = executeShellCommand("nmap localhost");
//		jTextPane1.setText(output);
//		try {
//			Thread.sleep(1000);
//		} catch (InterruptedException ex) {
//			Logger.getLogger(InterfaceServer.class.getName()).log(Level.SEVERE, null, ex);
//		}
//
//
//		server.waitClient();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                home = new javax.swing.JPanel();
                home_menu = new javax.swing.JPanel();
                menu_init = new javax.swing.JPanel();
                jLabel14 = new javax.swing.JLabel();
                init_bdd = new javax.swing.JButton();
                init_server = new javax.swing.JButton();
                jPanel11 = new javax.swing.JPanel();
                menu_service = new javax.swing.JPanel();
                jLabel15 = new javax.swing.JLabel();
                service_group = new javax.swing.JButton();
                jPanel5 = new javax.swing.JPanel();
                home_view = new javax.swing.JPanel();
                view_bdd = new javax.swing.JPanel();
                jLabel8 = new javax.swing.JLabel();
                jPanel3 = new javax.swing.JPanel();
                jLabel10 = new javax.swing.JLabel();
                jLabel13 = new javax.swing.JLabel();
                jLabel12 = new javax.swing.JLabel();
                jLabel16 = new javax.swing.JLabel();
                jLabel18 = new javax.swing.JLabel();
                jLabel17 = new javax.swing.JLabel();
                bdd_baseName = new javax.swing.JTextField();
                bdd_password = new javax.swing.JPasswordField();
                bdd_user = new javax.swing.JTextField();
                bdd_port = new javax.swing.JTextField();
                bdd_ip = new javax.swing.JTextField();
                bdd_connect = new javax.swing.JButton();
                bdd_init = new javax.swing.JButton();
                jScrollPane1 = new javax.swing.JScrollPane();
                bdd_console2 = new javax.swing.JTextArea();
                bdd_sgbd = new javax.swing.JComboBox<>();
                bdd_clearBase = new javax.swing.JButton();
                bdd_show = new javax.swing.JButton();
                jButton1 = new javax.swing.JButton();
                bdd_console = new javax.swing.JTextPane();
                view_server = new javax.swing.JPanel();
                jLabel3 = new javax.swing.JLabel();
                jPanel2 = new javax.swing.JPanel();
                jLabel9 = new javax.swing.JLabel();
                jLabel19 = new javax.swing.JLabel();
                server_port = new javax.swing.JTextField();
                jLabel20 = new javax.swing.JLabel();
                server_maxLog = new javax.swing.JTextField();
                server_connect = new javax.swing.JButton();
                server_console = new javax.swing.JTextPane();
                view_welcome = new javax.swing.JLabel();
                view_group = new javax.swing.JPanel();
                jScrollPane3 = new javax.swing.JScrollPane();
                home_view_group_table = new javax.swing.JTable();
                jButton2 = new javax.swing.JButton();
                home_group_inputNewGroup = new javax.swing.JTextField();
                jButton3 = new javax.swing.JButton();
                view_about = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();
                view_wait = new javax.swing.JPanel();
                jLabel11 = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setPreferredSize(new java.awt.Dimension(900, 600));
                getContentPane().setLayout(new java.awt.CardLayout(10, 10));

                home.setLayout(new java.awt.BorderLayout(10, 10));

                home_menu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
                home_menu.setMinimumSize(new java.awt.Dimension(0, 0));
                home_menu.setPreferredSize(new java.awt.Dimension(300, 900));
                home_menu.setLayout(new java.awt.GridLayout(3, 1));

                menu_init.setLayout(new java.awt.GridLayout(5, 1));

                jLabel14.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
                jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel14.setText("init");
                menu_init.add(jLabel14);

                init_bdd.setText("bdd");
                init_bdd.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                init_bddActionPerformed(evt);
                        }
                });
                menu_init.add(init_bdd);

                init_server.setText(" server");
                init_server.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                init_serverActionPerformed(evt);
                        }
                });
                menu_init.add(init_server);

                javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
                jPanel11.setLayout(jPanel11Layout);
                jPanel11Layout.setHorizontalGroup(
                        jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 294, Short.MAX_VALUE)
                );
                jPanel11Layout.setVerticalGroup(
                        jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 56, Short.MAX_VALUE)
                );

                menu_init.add(jPanel11);

                home_menu.add(menu_init);

                menu_service.setLayout(new java.awt.GridLayout(5, 1));

                jLabel15.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
                jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel15.setText("service");
                menu_service.add(jLabel15);

                service_group.setText("group");
                service_group.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                service_groupActionPerformed(evt);
                        }
                });
                menu_service.add(service_group);

                javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
                jPanel5.setLayout(jPanel5Layout);
                jPanel5Layout.setHorizontalGroup(
                        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 294, Short.MAX_VALUE)
                );
                jPanel5Layout.setVerticalGroup(
                        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 56, Short.MAX_VALUE)
                );

                menu_service.add(jPanel5);

                home_menu.add(menu_service);
                menu_service.setVisible(false);

                home.add(home_menu, java.awt.BorderLayout.WEST);

                home_view.setMinimumSize(new java.awt.Dimension(0, 0));
                home_view.setLayout(new java.awt.CardLayout());

                view_bdd.setLayout(new java.awt.BorderLayout());

                jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
                jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel8.setText("bdd");
                jLabel8.setMinimumSize(new java.awt.Dimension(50, 50));
                jLabel8.setPreferredSize(new java.awt.Dimension(50, 50));
                view_bdd.add(jLabel8, java.awt.BorderLayout.NORTH);

                jLabel10.setForeground(new java.awt.Color(102, 255, 102));
                jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/bdd.png"))); // NOI18N

                jLabel13.setText("ip");

                jLabel12.setText("port");

                jLabel16.setText("baseName");

                jLabel18.setText("user");

                jLabel17.setText("password");

                bdd_connect.setText("connect");
                bdd_connect.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bdd_connectActionPerformed(evt);
                        }
                });

                bdd_init.setText("init base");
                bdd_init.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bdd_initActionPerformed(evt);
                        }
                });

                bdd_console2.setColumns(20);
                bdd_console2.setRows(5);
                jScrollPane1.setViewportView(bdd_console2);

                bdd_sgbd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "postgres", "mysql" }));

                bdd_clearBase.setText("clear database");
                bdd_clearBase.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bdd_clearBaseActionPerformed(evt);
                        }
                });

                bdd_show.setText("show database");
                bdd_show.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bdd_showActionPerformed(evt);
                        }
                });

                jButton1.setText("use remote bdd");
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(100, 100, 100)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel16)
                                                        .addComponent(jLabel12)
                                                        .addComponent(jLabel13)
                                                        .addComponent(jLabel18)
                                                        .addComponent(jLabel17))
                                                .addGap(39, 39, 39)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(bdd_password, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                                                .addComponent(bdd_user)
                                                                .addComponent(bdd_baseName)
                                                                .addComponent(bdd_port))
                                                        .addComponent(bdd_ip, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(43, 43, 43)
                                                .addComponent(bdd_sgbd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(31, 31, 31)
                                                .addComponent(jLabel10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 212, Short.MAX_VALUE)
                                                .addComponent(bdd_connect)
                                                .addGap(206, 206, 206)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(bdd_init)
                                                .addGap(18, 18, 18)
                                                .addComponent(bdd_clearBase)
                                                .addGap(18, 18, 18)
                                                .addComponent(bdd_show)))
                                .addGap(25, 25, 25))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(174, 174, 174)
                                .addComponent(jButton1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                jPanel3Layout.setVerticalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(95, 95, 95)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(bdd_init)
                                                                        .addComponent(bdd_clearBase)
                                                                        .addComponent(bdd_show))
                                                                .addGap(34, 34, 34)
                                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                                                .addComponent(jLabel10)
                                                                                .addGap(18, 18, 18))
                                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                                                .addComponent(bdd_sgbd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(56, 56, 56)))
                                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jLabel13)
                                                                        .addComponent(bdd_ip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jLabel12)
                                                                        .addComponent(bdd_port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jLabel16)
                                                                        .addComponent(bdd_baseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jLabel18)
                                                                        .addComponent(bdd_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jLabel17)
                                                                        .addComponent(bdd_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(79, 79, 79)
                                                .addComponent(bdd_connect)))
                                .addGap(42, 42, 42)
                                .addComponent(jButton1)
                                .addContainerGap(245, Short.MAX_VALUE))
                );

                bdd_baseName.setText("universityRequest");
                bdd_password.setText("postgres");
                //bdd_password.setText("5qGw39Cg");
                bdd_password.setText("root");
                //bdd_user.setText("postgres");
                //bdd_user.setText("gauthier");
                bdd_user.setText("root");
                //bdd_user.setText("admin-universityrequest");
                //bdd_port.setText("5432");
                bdd_port.setText("3306");
                bdd_ip.setText("127.0.0.1");
                //bdd_ip.setText("database.university-request.fr");
                bdd_sgbd.setSelectedItem("mysql");

                view_bdd.add(jPanel3, java.awt.BorderLayout.CENTER);

                bdd_console.setPreferredSize(new java.awt.Dimension(0, 100));
                view_bdd.add(bdd_console, java.awt.BorderLayout.SOUTH);

                home_view.add(view_bdd, "bdd");

                view_server.setLayout(new java.awt.BorderLayout());

                jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
                jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel3.setText("Server");
                jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                jLabel3.setPreferredSize(new java.awt.Dimension(0, 50));
                view_server.add(jLabel3, java.awt.BorderLayout.PAGE_START);

                jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/server.png"))); // NOI18N

                jLabel19.setText("port");

                jLabel20.setText("maxLog");

                server_connect.setText("connect");
                server_connect.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                server_connectActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel19)
                                                        .addComponent(jLabel20))
                                                .addGap(49, 49, 49)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(server_port, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                                        .addComponent(server_maxLog, javax.swing.GroupLayout.Alignment.LEADING)))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(24, 24, 24)
                                                .addComponent(jLabel9)
                                                .addGap(52, 52, 52)
                                                .addComponent(server_connect)))
                                .addContainerGap(339, Short.MAX_VALUE))
                );
                jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(100, 100, 100)
                                                .addComponent(jLabel9)
                                                .addGap(18, 18, 18))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(server_connect)
                                                .addGap(44, 44, 44)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel19)
                                        .addComponent(server_port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel20)
                                        .addComponent(server_maxLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(223, Short.MAX_VALUE))
                );

                server_port.setText("5000");
                //server_port.setText("5432");
                server_maxLog.setText("100");

                view_server.add(jPanel2, java.awt.BorderLayout.LINE_START);

                server_console.setPreferredSize(new java.awt.Dimension(0, 300));
                view_server.add(server_console, java.awt.BorderLayout.SOUTH);

                home_view.add(view_server, "server");

                view_welcome.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
                view_welcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                view_welcome.setText("welcome in user interface");
                home_view.add(view_welcome, "welcome");

                home_view_group_table.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null},
                                {null},
                                {null},
                                {null}
                        },
                        new String [] {
                                "group"
                        }
                ) {
                        boolean[] canEdit = new boolean [] {
                                false
                        };

                        public boolean isCellEditable(int rowIndex, int columnIndex) {
                                return canEdit [columnIndex];
                        }
                });
                jScrollPane3.setViewportView(home_view_group_table);

                jButton2.setText("new group");
                jButton2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton2ActionPerformed(evt);
                        }
                });

                jButton3.setText("delete preselected row");
                jButton3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton3ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout view_groupLayout = new javax.swing.GroupLayout(view_group);
                view_group.setLayout(view_groupLayout);
                view_groupLayout.setHorizontalGroup(
                        view_groupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(view_groupLayout.createSequentialGroup()
                                .addGroup(view_groupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(view_groupLayout.createSequentialGroup()
                                                .addGap(135, 135, 135)
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(view_groupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(view_groupLayout.createSequentialGroup()
                                                                .addGap(134, 134, 134)
                                                                .addComponent(home_group_inputNewGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(view_groupLayout.createSequentialGroup()
                                                                .addGap(192, 192, 192)
                                                                .addComponent(jButton2))))
                                        .addGroup(view_groupLayout.createSequentialGroup()
                                                .addGap(249, 249, 249)
                                                .addComponent(jButton3)))
                                .addContainerGap(286, Short.MAX_VALUE))
                );
                view_groupLayout.setVerticalGroup(
                        view_groupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(view_groupLayout.createSequentialGroup()
                                .addGroup(view_groupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(view_groupLayout.createSequentialGroup()
                                                .addGap(117, 117, 117)
                                                .addComponent(jButton3)
                                                .addGap(29, 29, 29)
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(view_groupLayout.createSequentialGroup()
                                                .addGap(258, 258, 258)
                                                .addComponent(jButton2)
                                                .addGap(40, 40, 40)
                                                .addComponent(home_group_inputNewGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(254, Short.MAX_VALUE))
                );

                home_view.add(view_group, "group");

                jLabel1.setText("version 1.0");

                jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
                jLabel2.setText("universityRequest");

                jLabel4.setText("gauthier bouyjou");

                jLabel5.setText("amine benzerga");

                jLabel6.setText("jonathan lao-khan");

                javax.swing.GroupLayout view_aboutLayout = new javax.swing.GroupLayout(view_about);
                view_about.setLayout(view_aboutLayout);
                view_aboutLayout.setHorizontalGroup(
                        view_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(view_aboutLayout.createSequentialGroup()
                                .addGap(328, 328, 328)
                                .addGroup(view_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6))
                                .addContainerGap(701, Short.MAX_VALUE))
                );
                view_aboutLayout.setVerticalGroup(
                        view_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(view_aboutLayout.createSequentialGroup()
                                .addGap(156, 156, 156)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(538, Short.MAX_VALUE))
                );

                home_view.add(view_about, "about");

                view_wait.setLayout(new java.awt.CardLayout());

                jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/orange_load.gif"))); // NOI18N
                view_wait.add(jLabel11, "card2");

                home_view.add(view_wait, "wait");

                home.add(home_view, java.awt.BorderLayout.CENTER);
                view =(CardLayout)home_view.getLayout();

                getContentPane().add(home, "card4");

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void service_groupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_service_groupActionPerformed
                // TODO add your handling code here:
//		view_group.setVisible(true);
//		view_welcome.setVisible(false);
		show("group");
		majGroupTable();
        }//GEN-LAST:event_service_groupActionPerformed

        private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
		bdd.addGroup(home_group_inputNewGroup.getText());
		majGroupTable();
        }//GEN-LAST:event_jButton2ActionPerformed

        private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
		String nameGroup =(String)home_view_group_table.getValueAt(home_view_group_table.getSelectedRow(), home_view_group_table.getSelectedColumn());
		bdd.removeGroup(nameGroup);
		majGroupTable();
        }//GEN-LAST:event_jButton3ActionPerformed

        private void init_bddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_init_bddActionPerformed
		show("bdd");
        }//GEN-LAST:event_init_bddActionPerformed

        private void bdd_connectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdd_connectActionPerformed
		bddConnect();
        }//GEN-LAST:event_bdd_connectActionPerformed

	public void show(String tag) {
		view.show(home_view, tag);
	}

        private void init_serverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_init_serverActionPerformed
		show("server");
        }//GEN-LAST:event_init_serverActionPerformed

        private void server_connectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_server_connectActionPerformed
                // TODO add your handling code here:
		serverConnect();
        }//GEN-LAST:event_server_connectActionPerformed

        private void bdd_initActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdd_initActionPerformed
		//		String output = executeShellCommand("sh", "-c", "./src/bdd/initBase.sh ip gauthier universityrequest fuck");
		//		bdd_console2.setText(output);
		new Thread() {
			@Override
			public void run() {
				bdd.executeSqlScript(new File("src/bdd/build.sql"));
				bdd.executeSqlScript(new File("src/bdd/insertData.sql"));
				bdd.showTable(bdd_console2);
			}
			
		}.start();

		bdd_console2.setText("");
        }//GEN-LAST:event_bdd_initActionPerformed

        private void bdd_clearBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdd_clearBaseActionPerformed
                // TODO add your handling code here:
		bdd.clearTables();
		bdd.showTable(bdd_console2);
        }//GEN-LAST:event_bdd_clearBaseActionPerformed

        private void bdd_showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdd_showActionPerformed
                // TODO add your handling code here:
		bdd.showTable(bdd_console2);
        }//GEN-LAST:event_bdd_showActionPerformed

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                // TODO add your handling code here:
		bdd_ip.setText("database.university-request.fr");
		bdd_port.setText("3306");
		bdd_baseName.setText("universityrequest");
		bdd_user.setText("admin-universityrequest");
		bdd_password.setText("5qGw39Cg");
        }//GEN-LAST:event_jButton1ActionPerformed

	void majGroupTable() {
		Object[] myGroup =bdd.allGroups();
		System.out.println(myGroup);
		Object data[][] =new Object[myGroup.length][1];
		int i =0;
		for (Object o : myGroup) {
			data[i][0] =(String)o;
			i++;
		}
		String title[] ={"all groups"};
		home_view_group_table =new JTable(data, title);

                jScrollPane3.setViewportView(home_view_group_table);
	}

	public void serverConnect() {
		if (init_bdd.getBackground() == Color.green) {
			InterfaceServer ihm =this;
			show("wait");
			init_server.setBackground(Color.blue);
			
			new Thread() {
				public void run() {
					temporize();
					int port =Integer.parseInt(server_port.getText());
					int maxLog =Integer.parseInt(server_maxLog.getText());
					try {
						server = new Server(port, maxLog, bdd, ihm);
						String output = executeShellCommand("nmap", "localhost");
						server_console.setText(output);

						bdd_connect.setVisible(false);
						server_connect.setVisible(false);
						menu_service.setVisible(true);

						server.waitClient();

						init_server.setBackground(Color.green);
						show("welcome");

					} catch (IOException ex) {
						Logger.getLogger(InterfaceServer.class.getName()).log(Level.SEVERE, null, ex);
						init_server.setBackground(Color.red);
						server_console.setText(ex.getMessage());

						show("server");
					}
					
				}
			}.start();
		}
		else {
			init_server.setBackground(Color.darkGray);
		}
	}
	
	public void bddConnect() {
		show("wait");
		bdd_console.setText("");
		init_bdd.setBackground(Color.blue);
		
		new Thread() {
			public void run() {
				
				try {
					temporize();
					String baseName =bdd_baseName.getText();
					String ip =bdd_ip.getText();
					String port =bdd_port.getText();
					String user =bdd_user.getText();
					String passwd =bdd_password.getText();
					String sgbd =bdd_sgbd.getSelectedItem().toString();
//					bdd = new Bdd("universityRequest", "127.0.0.1", "5432", "postgres", "postgres");
					bdd = new Bdd(baseName, ip, port, user, passwd, sgbd);

					bdd_console.setText(bdd.uniq("select version()"));
					bdd.checkIntegrity(bdd_console2);
					bdd.showTable(bdd_console2);

					init_bdd.setBackground(Color.green);


				} catch (ClassNotFoundException | SQLException ex) {
					Logger.getLogger(InterfaceServer.class.getName()).log(Level.SEVERE, null, ex);
					init_bdd.setBackground(Color.red);
					bdd_console.setText(ex.getMessage());
				}
				show("bdd");
				
			}
		}.start();
	}
	
	
	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(InterfaceServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(InterfaceServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(InterfaceServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(InterfaceServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>


		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new InterfaceServer().setVisible(true);
//				new InterfaceServer();
			}
		});

//		InterfaceServer ihm =new InterfaceServer();
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JTextField bdd_baseName;
        private javax.swing.JButton bdd_clearBase;
        private javax.swing.JButton bdd_connect;
        private javax.swing.JTextPane bdd_console;
        private javax.swing.JTextArea bdd_console2;
        private javax.swing.JButton bdd_init;
        private javax.swing.JTextField bdd_ip;
        private javax.swing.JPasswordField bdd_password;
        private javax.swing.JTextField bdd_port;
        private javax.swing.JComboBox<String> bdd_sgbd;
        private javax.swing.JButton bdd_show;
        private javax.swing.JTextField bdd_user;
        private javax.swing.JPanel home;
        private javax.swing.JTextField home_group_inputNewGroup;
        private javax.swing.JPanel home_menu;
        private javax.swing.JPanel home_view;
        private javax.swing.JTable home_view_group_table;
        private javax.swing.JButton init_bdd;
        private javax.swing.JButton init_server;
        private javax.swing.JButton jButton1;
        private javax.swing.JButton jButton2;
        private javax.swing.JButton jButton3;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel10;
        private javax.swing.JLabel jLabel11;
        private javax.swing.JLabel jLabel12;
        private javax.swing.JLabel jLabel13;
        private javax.swing.JLabel jLabel14;
        private javax.swing.JLabel jLabel15;
        private javax.swing.JLabel jLabel16;
        private javax.swing.JLabel jLabel17;
        private javax.swing.JLabel jLabel18;
        private javax.swing.JLabel jLabel19;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel20;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JPanel jPanel11;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JPanel jPanel5;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane3;
        private javax.swing.JPanel menu_init;
        private javax.swing.JPanel menu_service;
        private javax.swing.JButton server_connect;
        private javax.swing.JTextPane server_console;
        private javax.swing.JTextField server_maxLog;
        private javax.swing.JTextField server_port;
        private javax.swing.JButton service_group;
        private javax.swing.JPanel view_about;
        private javax.swing.JPanel view_bdd;
        private javax.swing.JPanel view_group;
        private javax.swing.JPanel view_server;
        private javax.swing.JPanel view_wait;
        private javax.swing.JLabel view_welcome;
        // End of variables declaration//GEN-END:variables


	private String executeShellCommand(String... command) {
		StringBuffer output = new StringBuffer();
		Process p;
		try {
			p = Runtime.getRuntime().exec(command);
			p.waitFor();
			BufferedReader reader =
				new BufferedReader(new InputStreamReader(p.getInputStream()));
			
			String line = "";
			while ((line = reader.readLine())!= null) {
				output.append(line + "\n");
			}
			
		} catch (Exception e) {
			e.printStackTrace();
			return e.getMessage();
		}
		
		return output.toString();
	}

	private void temporize() {
		try {
			Thread.sleep(500);
		} catch (InterruptedException ex) {
			Logger.getLogger(InterfaceServer.class.getName()).log(Level.SEVERE, null, ex);
		}
	}

	public JTextArea getBdd_console2() {
		return bdd_console2;
	}
}
