/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package server;

import function.Function;
import java.awt.CardLayout;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStreamReader;
import java.lang.management.ManagementFactory;
import java.lang.management.RuntimeMXBean;
import java.sql.SQLException;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.SwingUtilities;

/**
 *
 * @author gauthier
 */
public class InterfaceServer extends javax.swing.JFrame {

	private static final long serialVersionUID = 1L;
	private Server server;
	private Bdd bdd;
	private CardLayout view;

	private String tag = Function.color(this);

	/**
	 * Creates new form Interface
	 */
	public InterfaceServer() {
		initComponents();

		this.setTitle("server application");
		this.setSize(1600, 900);
		this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		this.setLocationRelativeTo(null);
		this.setResizable(false);
		this.setVisible(true);
//		this.pack();

		new Thread() {
			@Override
			public void run() {
				bddConnect();
				temporize();
				temporize();
				serverConnect();
			}
		}.start();

//
//		try {
//			Thread.sleep(1000);
//		} catch (InterruptedException ex) {
//			Logger.getLogger(InterfaceServer.class.getName()).log(Level.SEVERE, null, ex);
//		}
//
//
//		server.waitClient();
//
//		try {
//			Thread.sleep(delay);
//		} catch (InterruptedException ex) {
//			Logger.getLogger(InterfaceServer.class.getName()).log(Level.SEVERE, null, ex);
//		}
//		jLabel11.setVisible(false);
////		jLabel7.setVisible(true);
//		if (bddFailed) {
//			home_view_bdd.setBackground(Color.red);
//			return;
//		}
//		else
//			home_view_bdd.setBackground(Color.green);
//
//		jTextField1.setText(bdd.uniq("select version()"));
//
//
//		jLabel15.setVisible(true);
//		server = new Server(5000, 100, bdd, this);
//
//		try {
//			Thread.sleep(delay);
//		} catch (InterruptedException ex) {
//			Logger.getLogger(InterfaceServer.class.getName()).log(Level.SEVERE, null, ex);
//		}
//
//		jLabel15.setVisible(false);
////		jLabel14.setVisible(true);
//		if (server.openingCommunication()) {
//			home_view_server.setBackground(Color.green);
//		} 
//		else {
//			home_view_server.setBackground(Color.red);
//			return;
//		}
//
//		String output = executeShellCommand("nmap localhost");
//		jTextPane1.setText(output);
//		try {
//			Thread.sleep(1000);
//		} catch (InterruptedException ex) {
//			Logger.getLogger(InterfaceServer.class.getName()).log(Level.SEVERE, null, ex);
//		}
//
//
//		server.waitClient();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                home = new javax.swing.JPanel();
                home_menu = new javax.swing.JPanel();
                menu_init = new javax.swing.JPanel();
                jLabel14 = new javax.swing.JLabel();
                init_bdd = new javax.swing.JButton();
                init_server = new javax.swing.JButton();
                jPanel11 = new javax.swing.JPanel();
                menu_service = new javax.swing.JPanel();
                jLabel15 = new javax.swing.JLabel();
                service_group = new javax.swing.JButton();
                service_user = new javax.swing.JButton();
                service_statistic = new javax.swing.JButton();
                jButton3 = new javax.swing.JButton();
                home_view = new javax.swing.JPanel();
                view_bdd = new javax.swing.JPanel();
                jLabel8 = new javax.swing.JLabel();
                jPanel3 = new javax.swing.JPanel();
                jLabel10 = new javax.swing.JLabel();
                jLabel13 = new javax.swing.JLabel();
                jLabel12 = new javax.swing.JLabel();
                jLabel16 = new javax.swing.JLabel();
                jLabel18 = new javax.swing.JLabel();
                jLabel17 = new javax.swing.JLabel();
                bdd_baseName = new javax.swing.JTextField();
                bdd_password = new javax.swing.JPasswordField();
                bdd_user = new javax.swing.JTextField();
                bdd_port = new javax.swing.JTextField();
                bdd_ip = new javax.swing.JTextField();
                bdd_connect = new javax.swing.JButton();
                bdd_init = new javax.swing.JButton();
                jScrollPane1 = new javax.swing.JScrollPane();
                bdd_console2 = new javax.swing.JTextArea();
                bdd_sgbd = new javax.swing.JComboBox<>();
                bdd_clearBase = new javax.swing.JButton();
                bdd_show = new javax.swing.JButton();
                jButton1 = new javax.swing.JButton();
                bdd_console = new javax.swing.JTextPane();
                view_server = new javax.swing.JPanel();
                jLabel3 = new javax.swing.JLabel();
                jPanel2 = new javax.swing.JPanel();
                jLabel9 = new javax.swing.JLabel();
                jLabel19 = new javax.swing.JLabel();
                server_port = new javax.swing.JTextField();
                jLabel20 = new javax.swing.JLabel();
                server_maxLog = new javax.swing.JTextField();
                server_connect = new javax.swing.JButton();
                server_console = new javax.swing.JTextPane();
                view_welcome = new javax.swing.JLabel();
                view_group = new javax.swing.JPanel();
                jScrollPane3 = new javax.swing.JScrollPane();
                home_view_group_table = new javax.swing.JTable();
                jButton2 = new javax.swing.JButton();
                home_group_inputNewGroup = new javax.swing.JTextField();
                jScrollPane2 = new javax.swing.JScrollPane();
                group_usersTable = new javax.swing.JTable();
                jButton4 = new javax.swing.JButton();
                jScrollPane4 = new javax.swing.JScrollPane();
                group_otherUserTable = new javax.swing.JTable();
                jButton5 = new javax.swing.JButton();
                view_user = new javax.swing.JPanel();
                jScrollPane5 = new javax.swing.JScrollPane();
                user_table = new javax.swing.JTable();
                jScrollPane6 = new javax.swing.JScrollPane();
                user_save = new javax.swing.JTable();
                jButton6 = new javax.swing.JButton();
                view_statistic = new javax.swing.JPanel();
                jPanel7 = new javax.swing.JPanel();
                jPanel1 = new javax.swing.JPanel();
                statistic_nbUsers = new javax.swing.JLabel();
                jLabel7 = new javax.swing.JLabel();
                jPanel8 = new javax.swing.JPanel();
                jPanel4 = new javax.swing.JPanel();
                statistic_nbGroups = new javax.swing.JLabel();
                jLabel21 = new javax.swing.JLabel();
                jPanel9 = new javax.swing.JPanel();
                jPanel12 = new javax.swing.JPanel();
                jLabel22 = new javax.swing.JLabel();
                statistic_nbLog = new javax.swing.JLabel();
                jPanel10 = new javax.swing.JPanel();
                jPanel14 = new javax.swing.JPanel();
                statistic_uptime = new javax.swing.JLabel();
                jLabel23 = new javax.swing.JLabel();
                jPanel6 = new javax.swing.JPanel();
                jPanel15 = new javax.swing.JPanel();
                jLabel24 = new javax.swing.JLabel();
                statistic_ticketUnresolve = new javax.swing.JLabel();
                jPanel13 = new javax.swing.JPanel();
                jPanel16 = new javax.swing.JPanel();
                statistic_ticketResolved = new javax.swing.JLabel();
                jLabel25 = new javax.swing.JLabel();
                view_about = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();
                view_wait = new javax.swing.JPanel();
                jLabel11 = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                getContentPane().setLayout(new java.awt.CardLayout(10, 10));

                home.setLayout(new java.awt.BorderLayout(10, 10));

                home_menu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
                home_menu.setMinimumSize(new java.awt.Dimension(0, 0));
                home_menu.setPreferredSize(new java.awt.Dimension(300, 900));
                home_menu.setLayout(new java.awt.GridLayout(3, 1));

                menu_init.setLayout(new java.awt.GridLayout(5, 1));

                jLabel14.setFont(new java.awt.Font("Ubuntu Light", 1, 24)); // NOI18N
                jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel14.setText("init");
                menu_init.add(jLabel14);

                init_bdd.setText("bdd");
                init_bdd.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                init_bddActionPerformed(evt);
                        }
                });
                menu_init.add(init_bdd);

                init_server.setText(" server");
                init_server.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                init_serverActionPerformed(evt);
                        }
                });
                menu_init.add(init_server);

                javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
                jPanel11.setLayout(jPanel11Layout);
                jPanel11Layout.setHorizontalGroup(
                        jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 294, Short.MAX_VALUE)
                );
                jPanel11Layout.setVerticalGroup(
                        jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 64, Short.MAX_VALUE)
                );

                menu_init.add(jPanel11);

                home_menu.add(menu_init);

                menu_service.setLayout(new java.awt.GridLayout(5, 1));

                jLabel15.setFont(new java.awt.Font("Ubuntu Light", 1, 24)); // NOI18N
                jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel15.setText("service");
                menu_service.add(jLabel15);

                service_group.setText("group");
                service_group.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                service_groupActionPerformed(evt);
                        }
                });
                menu_service.add(service_group);

                service_user.setText("user");
                service_user.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                service_userActionPerformed(evt);
                        }
                });
                menu_service.add(service_user);

                service_statistic.setText("statistic");
                service_statistic.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                service_statisticActionPerformed(evt);
                        }
                });
                menu_service.add(service_statistic);

                jButton3.setText("about");
                jButton3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton3ActionPerformed(evt);
                        }
                });
                menu_service.add(jButton3);

                home_menu.add(menu_service);
                menu_service.setVisible(false);

                home.add(home_menu, java.awt.BorderLayout.WEST);

                home_view.setMinimumSize(new java.awt.Dimension(0, 0));
                home_view.setLayout(new java.awt.CardLayout());

                view_bdd.setLayout(new java.awt.BorderLayout());

                jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
                jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel8.setText("bdd");
                jLabel8.setMinimumSize(new java.awt.Dimension(50, 50));
                jLabel8.setPreferredSize(new java.awt.Dimension(50, 50));
                view_bdd.add(jLabel8, java.awt.BorderLayout.NORTH);

                jLabel10.setForeground(new java.awt.Color(102, 255, 102));
                jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/bdd.png"))); // NOI18N

                jLabel13.setText("ip");

                jLabel12.setText("port");

                jLabel16.setText("baseName");

                jLabel18.setText("user");

                jLabel17.setText("password");

                bdd_connect.setText("connect");
                bdd_connect.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bdd_connectActionPerformed(evt);
                        }
                });

                bdd_init.setText("init base");
                bdd_init.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bdd_initActionPerformed(evt);
                        }
                });

                bdd_console2.setColumns(20);
                bdd_console2.setRows(5);
                jScrollPane1.setViewportView(bdd_console2);

                bdd_sgbd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "postgres", "mysql" }));

                bdd_clearBase.setText("clear database");
                bdd_clearBase.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bdd_clearBaseActionPerformed(evt);
                        }
                });

                bdd_show.setText("show database");
                bdd_show.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bdd_showActionPerformed(evt);
                        }
                });

                jButton1.setText("use remote database");
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(100, 100, 100)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel16)
                                                        .addComponent(jLabel12)
                                                        .addComponent(jLabel13)
                                                        .addComponent(jLabel18)
                                                        .addComponent(jLabel17))
                                                .addGap(39, 39, 39)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                .addComponent(bdd_user, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                                                                .addComponent(bdd_baseName, javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(bdd_port, javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(bdd_password))
                                                        .addComponent(bdd_ip, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(43, 43, 43)
                                                .addComponent(bdd_sgbd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(31, 31, 31)
                                                .addComponent(jLabel10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(bdd_connect)
                                                .addGap(68, 68, 68)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(bdd_init)
                                                .addGap(18, 18, 18)
                                                .addComponent(bdd_clearBase)
                                                .addGap(18, 18, 18)
                                                .addComponent(bdd_show))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(35, 35, 35)))
                                .addGap(130, 130, 130))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addComponent(jButton1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                jPanel3Layout.setVerticalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(bdd_init)
                                                        .addComponent(bdd_clearBase)
                                                        .addComponent(bdd_show))
                                                .addGap(265, 265, 265))
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(bdd_connect)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                                                .addComponent(jLabel10)
                                                                                .addGap(18, 18, 18))
                                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                                                .addComponent(bdd_sgbd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(56, 56, 56)))
                                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jLabel13)
                                                                        .addComponent(bdd_ip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jLabel12)
                                                                        .addComponent(bdd_port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jLabel16)
                                                                        .addComponent(bdd_baseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jLabel18)
                                                                        .addComponent(bdd_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jLabel17)
                                                                        .addComponent(bdd_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addGap(56, 56, 56)
                                .addComponent(jButton1)
                                .addContainerGap(362, Short.MAX_VALUE))
                );

                bdd_baseName.setText("universityRequest");
                //bdd_password.setText("postgres");
                //bdd_password.setText("5qGw39Cg");
                bdd_password.setText("root");
                //bdd_user.setText("postgres");
                //bdd_user.setText("gauthier");
                bdd_user.setText("root");
                //bdd_user.setText("admin-universityrequest");
                //bdd_port.setText("5432");
                bdd_port.setText("3306");
                bdd_ip.setText("127.0.0.1");
                //bdd_ip.setText("database.university-request.fr");
                bdd_sgbd.setSelectedItem("mysql");

                view_bdd.add(jPanel3, java.awt.BorderLayout.CENTER);

                bdd_console.setPreferredSize(new java.awt.Dimension(0, 100));
                view_bdd.add(bdd_console, java.awt.BorderLayout.SOUTH);

                home_view.add(view_bdd, "bdd");

                view_server.setLayout(new java.awt.BorderLayout());

                jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
                jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel3.setText("Server");
                jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                jLabel3.setPreferredSize(new java.awt.Dimension(0, 50));
                view_server.add(jLabel3, java.awt.BorderLayout.PAGE_START);

                jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/server.png"))); // NOI18N

                jLabel19.setText("port");

                jLabel20.setText("maxLog");

                server_connect.setText("connect");
                server_connect.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                server_connectActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel19)
                                                        .addComponent(jLabel20))
                                                .addGap(49, 49, 49)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(server_port, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                                        .addComponent(server_maxLog, javax.swing.GroupLayout.Alignment.LEADING)))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(24, 24, 24)
                                                .addComponent(jLabel9)
                                                .addGap(52, 52, 52)
                                                .addComponent(server_connect)))
                                .addContainerGap(339, Short.MAX_VALUE))
                );
                jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(100, 100, 100)
                                                .addComponent(jLabel9)
                                                .addGap(18, 18, 18))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(server_connect)
                                                .addGap(44, 44, 44)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel19)
                                        .addComponent(server_port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel20)
                                        .addComponent(server_maxLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(354, Short.MAX_VALUE))
                );

                server_port.setText("5000");
                //server_port.setText("5432");
                server_maxLog.setText("100");

                view_server.add(jPanel2, java.awt.BorderLayout.LINE_START);

                server_console.setPreferredSize(new java.awt.Dimension(0, 300));
                view_server.add(server_console, java.awt.BorderLayout.SOUTH);

                home_view.add(view_server, "server");

                view_welcome.setFont(new java.awt.Font("Ubuntu Light", 1, 48)); // NOI18N
                view_welcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                view_welcome.setText("welcome in user interface");
                home_view.add(view_welcome, "welcome");

                home_view_group_table.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null},
                                {null, null},
                                {null, null},
                                {null, null}
                        },
                        new String [] {
                                "group", "nbUsers"
                        }
                ) {
                        boolean[] canEdit = new boolean [] {
                                false, true
                        };

                        public boolean isCellEditable(int rowIndex, int columnIndex) {
                                return canEdit [columnIndex];
                        }
                });
                home_view_group_table.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                home_view_group_tableMouseClicked(evt);
                        }
                });
                jScrollPane3.setViewportView(home_view_group_table);

                jButton2.setText("new group");
                jButton2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton2ActionPerformed(evt);
                        }
                });

                group_usersTable.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null},
                                {null},
                                {null},
                                {null}
                        },
                        new String [] {
                                "users"
                        }
                ));
                jScrollPane2.setViewportView(group_usersTable);

                jButton4.setText("<html>\nremove\n<br>\ngroup\n<html>\n");
                jButton4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton4ActionPerformed(evt);
                        }
                });

                group_otherUserTable.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null},
                                {null},
                                {null},
                                {null}
                        },
                        new String [] {
                                "other users"
                        }
                ));
                jScrollPane4.setViewportView(group_otherUserTable);

                jButton5.setText("<html>swap<br>user<html>");
                jButton5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton5ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout view_groupLayout = new javax.swing.GroupLayout(view_group);
                view_group.setLayout(view_groupLayout);
                view_groupLayout.setHorizontalGroup(
                        view_groupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(view_groupLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(view_groupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(view_groupLayout.createSequentialGroup()
                                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(view_groupLayout.createSequentialGroup()
                                                .addComponent(jButton2)
                                                .addGap(18, 18, 18)
                                                .addComponent(home_group_inputNewGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                view_groupLayout.setVerticalGroup(
                        view_groupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, view_groupLayout.createSequentialGroup()
                                .addContainerGap(262, Short.MAX_VALUE)
                                .addGroup(view_groupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton2)
                                        .addComponent(home_group_inputNewGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(view_groupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(view_groupLayout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(view_groupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(view_groupLayout.createSequentialGroup()
                                                                .addGap(8, 8, 8)
                                                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(view_groupLayout.createSequentialGroup()
                                                .addGap(26, 26, 26)
                                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(262, Short.MAX_VALUE))
                );

                home_view.add(view_group, "group");

                user_table.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null, null},
                                {null, null, null, null, null},
                                {null, null, null, null, null},
                                {null, null, null, null, null}
                        },
                        new String [] {
                                "login", "password", "firstname", "name", "status"
                        }
                ));
                jScrollPane5.setViewportView(user_table);

                user_save.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null},
                                {null},
                                {null},
                                {null}
                        },
                        new String [] {
                                "save"
                        }
                ));
                jScrollPane6.setViewportView(user_save);

                jButton6.setText("remove");
                jButton6.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton6ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout view_userLayout = new javax.swing.GroupLayout(view_user);
                view_user.setLayout(view_userLayout);
                view_userLayout.setHorizontalGroup(
                        view_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(view_userLayout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(jButton6)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(212, Short.MAX_VALUE))
                );
                view_userLayout.setVerticalGroup(
                        view_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, view_userLayout.createSequentialGroup()
                                .addContainerGap(275, Short.MAX_VALUE)
                                .addGroup(view_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane5)
                                        .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
                                        .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(242, 242, 242))
                );

                home_view.add(view_user, "user");

                view_statistic.setLayout(new java.awt.GridLayout(3, 2, 10, 10));

                jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

                statistic_nbUsers.setText("123");

                jLabel7.setText("users");

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(36, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel7)
                                        .addComponent(statistic_nbUsers))
                                .addGap(46, 46, 46))
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(statistic_nbUsers)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addContainerGap(30, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
                jPanel7.setLayout(jPanel7Layout);
                jPanel7Layout.setHorizontalGroup(
                        jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addContainerGap(207, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(208, Short.MAX_VALUE))
                );
                jPanel7Layout.setVerticalGroup(
                        jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addContainerGap(107, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(108, Short.MAX_VALUE))
                );

                view_statistic.add(jPanel7);

                jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

                statistic_nbGroups.setText("12");

                jLabel21.setText("groups");

                javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
                jPanel4.setLayout(jPanel4Layout);
                jPanel4Layout.setHorizontalGroup(
                        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(32, 32, 32)
                                                .addComponent(statistic_nbGroups))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(23, 23, 23)
                                                .addComponent(jLabel21)))
                                .addContainerGap(27, Short.MAX_VALUE))
                );
                jPanel4Layout.setVerticalGroup(
                        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(statistic_nbGroups)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                                .addComponent(jLabel21)
                                .addGap(23, 23, 23))
                );

                javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
                jPanel8.setLayout(jPanel8Layout);
                jPanel8Layout.setHorizontalGroup(
                        jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addContainerGap(218, Short.MAX_VALUE)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(219, Short.MAX_VALUE))
                );
                jPanel8Layout.setVerticalGroup(
                        jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                                .addContainerGap(107, Short.MAX_VALUE)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(108, Short.MAX_VALUE))
                );

                view_statistic.add(jPanel8);

                jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

                jLabel22.setText("connected users");

                statistic_nbLog.setText("12");

                javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
                jPanel12.setLayout(jPanel12Layout);
                jPanel12Layout.setHorizontalGroup(
                        jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel12Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                                                .addComponent(jLabel22)
                                                .addContainerGap())
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                                                .addComponent(statistic_nbLog)
                                                .addGap(60, 60, 60))))
                );
                jPanel12Layout.setVerticalGroup(
                        jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(statistic_nbLog)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                .addComponent(jLabel22)
                                .addContainerGap())
                );

                javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
                jPanel9.setLayout(jPanel9Layout);
                jPanel9Layout.setHorizontalGroup(
                        jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                                .addContainerGap(197, Short.MAX_VALUE)
                                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(198, Short.MAX_VALUE))
                );
                jPanel9Layout.setVerticalGroup(
                        jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                                .addContainerGap(107, Short.MAX_VALUE)
                                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(108, Short.MAX_VALUE))
                );

                view_statistic.add(jPanel9);

                jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

                statistic_uptime.setText("date");

                jLabel23.setText("uptime");

                javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
                jPanel14.setLayout(jPanel14Layout);
                jPanel14Layout.setHorizontalGroup(
                        jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel14Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel23)
                                        .addComponent(statistic_uptime))
                                .addContainerGap(36, Short.MAX_VALUE))
                );
                jPanel14Layout.setVerticalGroup(
                        jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel14Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(statistic_uptime)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel23)
                                .addContainerGap(27, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
                jPanel10.setLayout(jPanel10Layout);
                jPanel10Layout.setHorizontalGroup(
                        jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                                .addContainerGap(218, Short.MAX_VALUE)
                                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(219, Short.MAX_VALUE))
                );
                jPanel10Layout.setVerticalGroup(
                        jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel10Layout.createSequentialGroup()
                                .addContainerGap(107, Short.MAX_VALUE)
                                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(108, Short.MAX_VALUE))
                );

                view_statistic.add(jPanel10);

                jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

                jLabel24.setText("tickets unresolved");

                statistic_ticketUnresolve.setText("12");

                javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
                jPanel15.setLayout(jPanel15Layout);
                jPanel15Layout.setHorizontalGroup(
                        jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel24)
                                .addContainerGap())
                        .addGroup(jPanel15Layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(statistic_ticketUnresolve)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                jPanel15Layout.setVerticalGroup(
                        jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                                .addContainerGap(29, Short.MAX_VALUE)
                                .addComponent(statistic_ticketUnresolve)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel24)
                                .addGap(23, 23, 23))
                );

                javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
                jPanel6.setLayout(jPanel6Layout);
                jPanel6Layout.setHorizontalGroup(
                        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addContainerGap(191, Short.MAX_VALUE)
                                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(191, Short.MAX_VALUE))
                );
                jPanel6Layout.setVerticalGroup(
                        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addContainerGap(107, Short.MAX_VALUE)
                                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(108, Short.MAX_VALUE))
                );

                view_statistic.add(jPanel6);

                jPanel13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

                statistic_ticketResolved.setText("63");

                jLabel25.setText("tickets resolved");

                javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
                jPanel16.setLayout(jPanel16Layout);
                jPanel16Layout.setHorizontalGroup(
                        jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel16Layout.createSequentialGroup()
                                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel16Layout.createSequentialGroup()
                                                .addGap(36, 36, 36)
                                                .addComponent(statistic_ticketResolved))
                                        .addGroup(jPanel16Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabel25)))
                                .addContainerGap(48, Short.MAX_VALUE))
                );
                jPanel16Layout.setVerticalGroup(
                        jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel16Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(statistic_ticketResolved)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addComponent(jLabel25)
                                .addGap(28, 28, 28))
                );

                javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
                jPanel13.setLayout(jPanel13Layout);
                jPanel13Layout.setHorizontalGroup(
                        jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                                .addContainerGap(182, Short.MAX_VALUE)
                                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(182, Short.MAX_VALUE))
                );
                jPanel13Layout.setVerticalGroup(
                        jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel13Layout.createSequentialGroup()
                                .addContainerGap(107, Short.MAX_VALUE)
                                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(108, Short.MAX_VALUE))
                );

                view_statistic.add(jPanel13);

                home_view.add(view_statistic, "statistic");

                jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
                jLabel1.setText("version 1.0");

                jLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
                jLabel2.setText("universityRequest");

                jLabel4.setText("gauthier bouyjou     java development");

                jLabel5.setText("amine benzerga     designer interface");

                jLabel6.setText("jonathan lao-khan     network resolution");

                javax.swing.GroupLayout view_aboutLayout = new javax.swing.GroupLayout(view_about);
                view_about.setLayout(view_aboutLayout);
                view_aboutLayout.setHorizontalGroup(
                        view_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(view_aboutLayout.createSequentialGroup()
                                .addContainerGap(362, Short.MAX_VALUE)
                                .addGroup(view_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6))
                                .addContainerGap(363, Short.MAX_VALUE))
                );
                view_aboutLayout.setVerticalGroup(
                        view_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(view_aboutLayout.createSequentialGroup()
                                .addContainerGap(402, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(402, Short.MAX_VALUE))
                );

                home_view.add(view_about, "about");

                view_wait.setLayout(new java.awt.CardLayout());

                jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/orange_load.gif"))); // NOI18N
                view_wait.add(jLabel11, "card2");

                home_view.add(view_wait, "wait");

                home.add(home_view, java.awt.BorderLayout.CENTER);
                view =(CardLayout)home_view.getLayout();

                getContentPane().add(home, "card4");

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void service_groupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_service_groupActionPerformed
		// TODO add your handling code here:
//		view_group.setVisible(true);
//		view_welcome.setVisible(false);
		show("group");
		majGroupTable();
        }//GEN-LAST:event_service_groupActionPerformed

        private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
		bdd.addGroup(home_group_inputNewGroup.getText());
		majGroupTable();
        }//GEN-LAST:event_jButton2ActionPerformed

        private void init_bddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_init_bddActionPerformed
		show("bdd");
        }//GEN-LAST:event_init_bddActionPerformed

        private void bdd_connectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdd_connectActionPerformed
		bddConnect();
        }//GEN-LAST:event_bdd_connectActionPerformed

	public void show(String tag) {
		view.show(home_view, tag);
	}

        private void init_serverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_init_serverActionPerformed
		show("server");
        }//GEN-LAST:event_init_serverActionPerformed

        private void server_connectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_server_connectActionPerformed
		// TODO add your handling code here:
		serverConnect();
        }//GEN-LAST:event_server_connectActionPerformed

        private void bdd_initActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdd_initActionPerformed
		//		String output = executeShellCommand("sh", "-c", "./src/bdd/initBase.sh ip gauthier universityrequest fuck");
		//		bdd_console2.setText(output);
		new Thread() {
			@Override
			public void run() {
				bdd.executeSqlScript(new File("src/bdd/build.sql"));
				bdd.executeSqlScript(new File("src/bdd/insertData.sql"));

//		bdd.checkIntegrity(bdd_console2);
				bdd.showTable(bdd_console2);
			}

		}.start();
		bdd_console2.setText("");
        }//GEN-LAST:event_bdd_initActionPerformed

        private void bdd_clearBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdd_clearBaseActionPerformed
		// TODO add your handling code here:
		bdd.clearTables();
		bdd.showTable(bdd_console2);
        }//GEN-LAST:event_bdd_clearBaseActionPerformed

        private void bdd_showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdd_showActionPerformed
		// TODO add your handling code here:
		bdd.showTable(bdd_console2);
        }//GEN-LAST:event_bdd_showActionPerformed

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		bdd_ip.setText("database.university-request.fr");
		bdd_port.setText("3306");
		bdd_baseName.setText("universityrequest");
		bdd_user.setText("admin-universityrequest");
		bdd_password.setText("5qGw39Cg");
        }//GEN-LAST:event_jButton1ActionPerformed

        private void home_view_group_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_view_group_tableMouseClicked
		// TODO add your handling code here:
		String nameGroup = (String) home_view_group_table.getValueAt(home_view_group_table.getSelectedRow(), 0);
		System.out.println(nameGroup);
		majUsersTable(nameGroup);
        }//GEN-LAST:event_home_view_group_tableMouseClicked

        private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
		// TODO add your handling code here:
//		String user =(String)group_usersTable.getValueAt(group_usersTable.getSelectedRow(), 0);
//		String group =(String)home_view_group_table.getValueAt(home_view_group_table.getSelectedRow(), 0);
//		System.out.println("del " +user +" in " +group);
//		bdd.delUserInGroup(user, group);
//		majUsersTable(group);

		String nameGroup = (String) home_view_group_table.getValueAt(home_view_group_table.getSelectedRow(), 0);
		bdd.removeGroup(nameGroup);
		majGroupTable();
        }//GEN-LAST:event_jButton4ActionPerformed

	public String getSelectedValueInTable(JTable table) {
		int row = table.getSelectedRow();
		if (row == -1) {
			return "";
		} else {
			return (String) table.getValueAt(row, 0);
		}
	}

        private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
		// TODO add your handling code here:
		String userInGroup = getSelectedValueInTable(group_usersTable);
		String otherUsers = getSelectedValueInTable(group_otherUserTable);
		String group = getSelectedValueInTable(home_view_group_table);

		System.out.println("userInGroup(" + userInGroup + ") otherUsers(" + otherUsers + ") group(" + group + ")");

		if (!userInGroup.equals("")) {
			System.out.println("del " + userInGroup + " in " + group);
			bdd.delUserInGroup(userInGroup, group);
		} else {
			System.out.println("add " + otherUsers + " in " + group);
			bdd.addUserInGroup(otherUsers, group);
		}

		majUsersTable(group);
		majGroupTable();
        }//GEN-LAST:event_jButton5ActionPerformed

        private void service_statisticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_service_statisticActionPerformed
		// TODO add your handling code here:
		statistic_nbUsers.setText(bdd.getNbUsers());
		statistic_nbGroups.setText(bdd.getNbGroups());
		statistic_nbLog.setText(server.getNbThreads().toString());
		RuntimeMXBean rb = ManagementFactory.getRuntimeMXBean();
		statistic_uptime.setText("up " + rb.getUptime() + " ms");
		statistic_ticketUnresolve.setText((String) "12");
		statistic_ticketResolved.setText((String) "2");
		show("statistic");
        }//GEN-LAST:event_service_statisticActionPerformed

        private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
		// TODO add your handling code here:
		show("about");
        }//GEN-LAST:event_jButton3ActionPerformed

        private void service_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_service_userActionPerformed
		show("user");
		user_majTable();
        }//GEN-LAST:event_service_userActionPerformed

        private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
                // TODO add your handling code here:
		int row =user_table.getSelectedRow();
		if (row != -1) {
			String login =(String)user_table.getValueAt(row, 0);
			System.out.println("del " +login +" in table");
			bdd.delUserInGroup(login);
			user_majTable();
		}
        }//GEN-LAST:event_jButton6ActionPerformed

	public void user_majSaveTable() {
		String title[] = {"save"};
		int len =user_table.getRowCount();
		System.out.println("len =" +len);
		Object[][] data =new String[len][1];
		for (int i =0; i <len; i++) {
//			data[i][0] =new JButton("ok");
			data[i][0] ="ok";
		}
		user_save = new JTable(data, title);

		user_save.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				int line = user_save.getSelectedRow();
				System.out.println("saveLine =" +line);
				String[] userRow =new String[5];

				System.out.print("modify table ");
				for (int i =0; i <5; i++) {
					userRow[i] =(String)user_table.getValueAt(line, i);
					System.out.print(userRow[i] +" ");
				}
				System.out.println("");

				if (line <user_save.getRowCount() -1)
					bdd.changeUserRow(userRow);
				else
					bdd.newUser(userRow[0], userRow[1], userRow[2], userRow[3], userRow[4]);

				user_majTable();
			}
		});


		jScrollPane6.setViewportView(user_save);
		System.out.println("fuck");
	}

	public void user_majTable() {
		String title[] = {"login", "password", "firstname", "name", "status"};
		String m[][] = bdd.usersTable();

		String data[][] =new String[m.length +1][5];
		for (int i =0; i <m.length +1; i++) {
			for (int j =0; j <5; j++) {
				if (i <m.length)
					data[i][j] =m[i][j];
				else
					data[i][j] ="";
			}
		}
		user_table = new JTable(data, title);


		jScrollPane5.setViewportView(user_table);

		user_majSaveTable();
	}

	void majGroupTable() {
//		Object[] myGroup =bdd.allGroups();
//		System.out.println(myGroup);
//		Object data[][] =new Object[myGroup.length][1];
//		int i =0;
//		for (Object o : myGroup) {
//			data[i][0] =(String)o;
//			i++;
//		}
		String title[] = {"all groups", "nbUsers"};
		String data[][] = bdd.allGroupsWithNbUser();
		home_view_group_table = new JTable(data, title);

		home_view_group_table.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				home_view_group_tableMouseClicked(evt);
			}
		});

		jScrollPane3.setViewportView(home_view_group_table);
	}

	public void majUsersTable(String group) {
		String title[] = {"users"};
		String data[][] = bdd.allUsersOfGroup(group);

		if (data == null) {
			group_usersTable = new JTable(new Object[][]{{null}}, title);
		} else {
			group_usersTable = new JTable(data, title);
		}

		jScrollPane2.setViewportView(group_usersTable);

		String title2[] = {"other users"};
		String data2[][] = bdd.otherUsersOfGroup(group);

		group_otherUserTable = new JTable(data2, title2);

		jScrollPane4.setViewportView(group_otherUserTable);
	}

	public void serverConnect() {
		if (init_bdd.getBackground() == Color.green) {
			InterfaceServer ihm = this;
			show("wait");
			init_server.setBackground(Color.blue);

			new Thread() {
				public void run() {
					temporize();
					int port = Integer.parseInt(server_port.getText());
					int maxLog = Integer.parseInt(server_maxLog.getText());
					try {
						server = new Server(port, maxLog, bdd, ihm);
						String output = executeShellCommand("nmap", "localhost");
						server_console.setText(output);

						bdd_connect.setVisible(false);
						server_connect.setVisible(false);
						menu_service.setVisible(true);

						server.waitClient();

						init_server.setBackground(Color.green);
						show("welcome");

					} catch (IOException ex) {
						Logger.getLogger(InterfaceServer.class.getName()).log(Level.SEVERE, null, ex);
						init_server.setBackground(Color.red);
						server_console.setText(ex.getMessage());

						show("server");
					}

				}
			}.start();
		} else {
			init_server.setBackground(Color.darkGray);
		}
	}

	public void bddConnect() {
		show("wait");
		bdd_console.setText("");
		init_bdd.setBackground(Color.blue);

		new Thread() {
			public void run() {

				try {
					temporize();
					String baseName = bdd_baseName.getText();
					String ip = bdd_ip.getText();
					String port = bdd_port.getText();
					String user = bdd_user.getText();
					String passwd = bdd_password.getText();
					String sgbd = bdd_sgbd.getSelectedItem().toString();
//					bdd = new Bdd("universityRequest", "127.0.0.1", "5432", "postgres", "postgres");
					bdd = new Bdd(baseName, ip, port, user, passwd, sgbd);

					bdd_console.setText(bdd.uniq("select version()"));
					bdd.checkIntegrity(bdd_console2);
					bdd.showTable(bdd_console2);

					init_bdd.setBackground(Color.green);

				} catch (ClassNotFoundException | SQLException ex) {
					Logger.getLogger(InterfaceServer.class.getName()).log(Level.SEVERE, null, ex);
					init_bdd.setBackground(Color.red);
					bdd_console.setText(ex.getMessage());
				}
				show("bdd");

			}
		}.start();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(InterfaceServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(InterfaceServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(InterfaceServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(InterfaceServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>


		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new InterfaceServer().setVisible(true);
//				new InterfaceServer();
			}
		});

//		InterfaceServer ihm =new InterfaceServer();
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JTextField bdd_baseName;
        private javax.swing.JButton bdd_clearBase;
        private javax.swing.JButton bdd_connect;
        private javax.swing.JTextPane bdd_console;
        private javax.swing.JTextArea bdd_console2;
        private javax.swing.JButton bdd_init;
        private javax.swing.JTextField bdd_ip;
        private javax.swing.JPasswordField bdd_password;
        private javax.swing.JTextField bdd_port;
        private javax.swing.JComboBox<String> bdd_sgbd;
        private javax.swing.JButton bdd_show;
        private javax.swing.JTextField bdd_user;
        private javax.swing.JTable group_otherUserTable;
        private javax.swing.JTable group_usersTable;
        private javax.swing.JPanel home;
        private javax.swing.JTextField home_group_inputNewGroup;
        private javax.swing.JPanel home_menu;
        private javax.swing.JPanel home_view;
        private javax.swing.JTable home_view_group_table;
        private javax.swing.JButton init_bdd;
        private javax.swing.JButton init_server;
        private javax.swing.JButton jButton1;
        private javax.swing.JButton jButton2;
        private javax.swing.JButton jButton3;
        private javax.swing.JButton jButton4;
        private javax.swing.JButton jButton5;
        private javax.swing.JButton jButton6;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel10;
        private javax.swing.JLabel jLabel11;
        private javax.swing.JLabel jLabel12;
        private javax.swing.JLabel jLabel13;
        private javax.swing.JLabel jLabel14;
        private javax.swing.JLabel jLabel15;
        private javax.swing.JLabel jLabel16;
        private javax.swing.JLabel jLabel17;
        private javax.swing.JLabel jLabel18;
        private javax.swing.JLabel jLabel19;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel20;
        private javax.swing.JLabel jLabel21;
        private javax.swing.JLabel jLabel22;
        private javax.swing.JLabel jLabel23;
        private javax.swing.JLabel jLabel24;
        private javax.swing.JLabel jLabel25;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel10;
        private javax.swing.JPanel jPanel11;
        private javax.swing.JPanel jPanel12;
        private javax.swing.JPanel jPanel13;
        private javax.swing.JPanel jPanel14;
        private javax.swing.JPanel jPanel15;
        private javax.swing.JPanel jPanel16;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JPanel jPanel4;
        private javax.swing.JPanel jPanel6;
        private javax.swing.JPanel jPanel7;
        private javax.swing.JPanel jPanel8;
        private javax.swing.JPanel jPanel9;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JScrollPane jScrollPane3;
        private javax.swing.JScrollPane jScrollPane4;
        private javax.swing.JScrollPane jScrollPane5;
        private javax.swing.JScrollPane jScrollPane6;
        private javax.swing.JPanel menu_init;
        private javax.swing.JPanel menu_service;
        private javax.swing.JButton server_connect;
        private javax.swing.JTextPane server_console;
        private javax.swing.JTextField server_maxLog;
        private javax.swing.JTextField server_port;
        private javax.swing.JButton service_group;
        private javax.swing.JButton service_statistic;
        private javax.swing.JButton service_user;
        private javax.swing.JLabel statistic_nbGroups;
        private javax.swing.JLabel statistic_nbLog;
        private javax.swing.JLabel statistic_nbUsers;
        private javax.swing.JLabel statistic_ticketResolved;
        private javax.swing.JLabel statistic_ticketUnresolve;
        private javax.swing.JLabel statistic_uptime;
        private javax.swing.JTable user_save;
        private javax.swing.JTable user_table;
        private javax.swing.JPanel view_about;
        private javax.swing.JPanel view_bdd;
        private javax.swing.JPanel view_group;
        private javax.swing.JPanel view_server;
        private javax.swing.JPanel view_statistic;
        private javax.swing.JPanel view_user;
        private javax.swing.JPanel view_wait;
        private javax.swing.JLabel view_welcome;
        // End of variables declaration//GEN-END:variables

	private String executeShellCommand(String... command) {
		StringBuffer output = new StringBuffer();
		Process p;
		try {
			p = Runtime.getRuntime().exec(command);
			p.waitFor();
			BufferedReader reader
				= new BufferedReader(new InputStreamReader(p.getInputStream()));

			String line = "";
			while ((line = reader.readLine()) != null) {
				output.append(line + "\n");
			}

		} catch (Exception e) {
			e.printStackTrace();
			return e.getMessage();
		}

		return output.toString();
	}

	private void temporize() {
		try {
			Thread.sleep(500);
		} catch (InterruptedException ex) {
			Logger.getLogger(InterfaceServer.class.getName()).log(Level.SEVERE, null, ex);
		}
	}

	public JTextArea getBdd_console2() {
		return bdd_console2;
	}

}
