/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

import function.Function;
import java.io.IOException;
import java.util.Arrays;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import network.RequestName;

/**
 *
 * @author gauthier
 */
public class InterfaceClient extends javax.swing.JFrame {
	private static final long serialVersionUID =1L;
	private Client client;
	private boolean retry;

	private String tag =Function.color(this);

	/**
	 * Creates new form Interface
	 */
	public InterfaceClient() {
		initComponents();

		this.setTitle("client application");
		this.setSize(1600, 900);
		this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		this.setLocationRelativeTo(null);
		this.setResizable(false);

		this.setVisible(true);


		boolean connected =false;
		while (! connected) {
			try {
				try {
					Thread.sleep(1000);
				} catch (InterruptedException ex) {
					Logger.getLogger(InterfaceClient.class.getName()).log(Level.SEVERE, null, ex);
				}

				client = new Client("127.0.0.1", 5000, this);
				connected =true;


			} catch (IOException ex) {
				Logger.getLogger(InterfaceClient.class.getName()).log(Level.SEVERE, null, ex);
				serverNotFound.setVisible(true);
				serverConnect.setVisible(false);

				retry =false;
				while (! retry) {
					try {
						Thread.sleep(1000);
					} catch (InterruptedException ex1) {
						Logger.getLogger(InterfaceClient.class.getName()).log(Level.SEVERE, null, ex1);
					}
				}
				serverConnect.setVisible(true);
				serverNotFound.setVisible(false);
			}
		}

		identification.setVisible(true);
		serverConnect.setVisible(false);


	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                serverConnect = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                serverNotFound = new javax.swing.JPanel();
                jLabel3 = new javax.swing.JLabel();
                jButton1 = new javax.swing.JButton();
                identification = new javax.swing.JPanel();
                jLabel4 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                passwdInput = new javax.swing.JPasswordField();
                loginInput = new javax.swing.JTextField();
                jButton2 = new javax.swing.JButton();
                jButton3 = new javax.swing.JButton();
                home_wrong = new javax.swing.JLabel();
                newUser = new javax.swing.JPanel();
                jLabel6 = new javax.swing.JLabel();
                jLabel8 = new javax.swing.JLabel();
                inputName = new javax.swing.JTextField();
                inputPasswd = new javax.swing.JPasswordField();
                inputStatus = new javax.swing.JComboBox<>();
                jLabel12 = new javax.swing.JLabel();
                jButton4 = new javax.swing.JButton();
                jButton5 = new javax.swing.JButton();
                jLabel7 = new javax.swing.JLabel();
                jLabel9 = new javax.swing.JLabel();
                newUser_name = new javax.swing.JTextField();
                newUser_firstName = new javax.swing.JTextField();
                home = new javax.swing.JPanel();
                jPanel1 = new javax.swing.JPanel();
                jScrollPane1 = new javax.swing.JScrollPane();
                tree = new javax.swing.JTree();
                jPanel4 = new javax.swing.JPanel();
                jPanel3 = new javax.swing.JPanel();
                home_userName = new javax.swing.JLabel();
                home_group = new javax.swing.JButton();
                jPanel5 = new javax.swing.JPanel();
                group = new javax.swing.JPanel();
                jScrollPane2 = new javax.swing.JScrollPane();
                group_table = new javax.swing.JTable();
                group_back = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                getContentPane().setLayout(new java.awt.CardLayout());

                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/server.gif"))); // NOI18N
                jLabel1.setText("jLabel1");

                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/serverConnect.gif"))); // NOI18N

                javax.swing.GroupLayout serverConnectLayout = new javax.swing.GroupLayout(serverConnect);
                serverConnect.setLayout(serverConnectLayout);
                serverConnectLayout.setHorizontalGroup(
                        serverConnectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(serverConnectLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)
                                .addComponent(jLabel2)
                                .addContainerGap(644, Short.MAX_VALUE))
                );
                serverConnectLayout.setVerticalGroup(
                        serverConnectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(serverConnectLayout.createSequentialGroup()
                                .addGroup(serverConnectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(serverConnectLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(serverConnectLayout.createSequentialGroup()
                                                .addGap(206, 206, 206)
                                                .addComponent(jLabel2)))
                                .addContainerGap(414, Short.MAX_VALUE))
                );

                getContentPane().add(serverConnect, "card2");

                jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/serverNotFound.png"))); // NOI18N

                jButton1.setText("retry");
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout serverNotFoundLayout = new javax.swing.GroupLayout(serverNotFound);
                serverNotFound.setLayout(serverNotFoundLayout);
                serverNotFoundLayout.setHorizontalGroup(
                        serverNotFoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(serverNotFoundLayout.createSequentialGroup()
                                .addGroup(serverNotFoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(serverNotFoundLayout.createSequentialGroup()
                                                .addGap(174, 174, 174)
                                                .addComponent(jLabel3))
                                        .addGroup(serverNotFoundLayout.createSequentialGroup()
                                                .addGap(336, 336, 336)
                                                .addComponent(jButton1)))
                                .addContainerGap(1019, Short.MAX_VALUE))
                );
                serverNotFoundLayout.setVerticalGroup(
                        serverNotFoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(serverNotFoundLayout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(jLabel3)
                                .addGap(47, 47, 47)
                                .addComponent(jButton1)
                                .addContainerGap(422, Short.MAX_VALUE))
                );

                getContentPane().add(serverNotFound, "card3");

                jLabel4.setText("login");

                jLabel5.setText("passwd");

                passwdInput.setText("fuck");
                passwdInput.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                passwdInputActionPerformed(evt);
                        }
                });

                loginInput.setText("gauthier");

                jButton2.setText("connection");
                jButton2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton2ActionPerformed(evt);
                        }
                });

                jButton3.setText("new user");
                jButton3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton3ActionPerformed(evt);
                        }
                });

                home_wrong.setForeground(new java.awt.Color(255, 0, 0));
                home_wrong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/wrong.png"))); // NOI18N
                home_wrong.setText("wrong login or password");

                javax.swing.GroupLayout identificationLayout = new javax.swing.GroupLayout(identification);
                identification.setLayout(identificationLayout);
                identificationLayout.setHorizontalGroup(
                        identificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(identificationLayout.createSequentialGroup()
                                .addGroup(identificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(identificationLayout.createSequentialGroup()
                                                .addGap(463, 463, 463)
                                                .addComponent(home_wrong))
                                        .addGroup(identificationLayout.createSequentialGroup()
                                                .addGap(372, 372, 372)
                                                .addGroup(identificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel5)
                                                        .addComponent(jLabel4))
                                                .addGap(91, 91, 91)
                                                .addGroup(identificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(identificationLayout.createSequentialGroup()
                                                                .addComponent(jButton2)
                                                                .addGap(270, 270, 270)
                                                                .addComponent(jButton3))
                                                        .addComponent(passwdInput, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(loginInput, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(600, Short.MAX_VALUE))
                );
                identificationLayout.setVerticalGroup(
                        identificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(identificationLayout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(home_wrong)
                                .addGap(80, 80, 80)
                                .addGroup(identificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(loginInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(52, 52, 52)
                                .addGroup(identificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(passwdInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(68, 68, 68)
                                .addGroup(identificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton2)
                                        .addComponent(jButton3))
                                .addContainerGap(414, Short.MAX_VALUE))
                );

                home_wrong.setVisible(false);

                getContentPane().add(identification, "card4");

                jLabel6.setText("login");

                jLabel8.setText("password");

                inputStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "student", "professor", "service" }));

                jLabel12.setText("status");

                jButton4.setText("create new user");
                jButton4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton4ActionPerformed(evt);
                        }
                });

                jButton5.setText("back");
                jButton5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton5ActionPerformed(evt);
                        }
                });

                jLabel7.setText("firstName");

                jLabel9.setText("name");

                javax.swing.GroupLayout newUserLayout = new javax.swing.GroupLayout(newUser);
                newUser.setLayout(newUserLayout);
                newUserLayout.setHorizontalGroup(
                        newUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(newUserLayout.createSequentialGroup()
                                .addGroup(newUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(newUserLayout.createSequentialGroup()
                                                .addGap(342, 342, 342)
                                                .addGroup(newUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel6)
                                                        .addComponent(jLabel8)
                                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newUserLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(newUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(newUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(newUserLayout.createSequentialGroup()
                                                .addGroup(newUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(newUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(inputStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(inputPasswd, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                                                .addComponent(inputName))
                                                        .addComponent(newUser_name, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(newUserLayout.createSequentialGroup()
                                                .addGroup(newUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(newUserLayout.createSequentialGroup()
                                                                .addComponent(jButton4)
                                                                .addGap(273, 273, 273)
                                                                .addComponent(jButton5))
                                                        .addComponent(newUser_firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 680, Short.MAX_VALUE))))
                );
                newUserLayout.setVerticalGroup(
                        newUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(newUserLayout.createSequentialGroup()
                                .addGap(174, 174, 174)
                                .addGroup(newUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addGroup(newUserLayout.createSequentialGroup()
                                                .addComponent(inputName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(12, 12, 12)
                                                .addGroup(newUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel8)
                                                        .addComponent(inputPasswd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(30, 30, 30)
                                .addGroup(newUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(newUser_firstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(newUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(newUser_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9))
                                .addGap(19, 19, 19)
                                .addGroup(newUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(inputStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel12))
                                .addGap(45, 45, 45)
                                .addGroup(newUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton4)
                                        .addComponent(jButton5))
                                .addContainerGap(483, Short.MAX_VALUE))
                );

                getContentPane().add(newUser, "card5");

                home.setBackground(new java.awt.Color(0, 0, 0));
                home.setMaximumSize(new java.awt.Dimension(1600, 900));
                home.setMinimumSize(new java.awt.Dimension(1600, 900));
                home.setLayout(new java.awt.BorderLayout(1, 1));

                jPanel1.setMaximumSize(new java.awt.Dimension(10, 900));
                jPanel1.setMinimumSize(new java.awt.Dimension(10, 900));
                jPanel1.setPreferredSize(new java.awt.Dimension(100, 500));

                jScrollPane1.setViewportView(tree);

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(136, Short.MAX_VALUE))
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(383, Short.MAX_VALUE))
                );

                home.add(jPanel1, java.awt.BorderLayout.CENTER);

                jPanel4.setBackground(new java.awt.Color(0, 0, 0));
                jPanel4.setLayout(new java.awt.BorderLayout(1, 1));

                home_userName.setText("login");

                home_group.setText("add/remove  group");
                home_group.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                home_groupActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(home_userName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 779, Short.MAX_VALUE)
                                .addComponent(home_group)
                                .addGap(103, 103, 103))
                );
                jPanel3Layout.setVerticalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(home_group)
                                        .addComponent(home_userName))
                                .addContainerGap(481, Short.MAX_VALUE))
                );

                jPanel4.add(jPanel3, java.awt.BorderLayout.PAGE_START);

                javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
                jPanel5.setLayout(jPanel5Layout);
                jPanel5Layout.setHorizontalGroup(
                        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1096, Short.MAX_VALUE)
                );
                jPanel5Layout.setVerticalGroup(
                        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 381, Short.MAX_VALUE)
                );

                jPanel4.add(jPanel5, java.awt.BorderLayout.CENTER);

                home.add(jPanel4, java.awt.BorderLayout.LINE_END);

                getContentPane().add(home, "card6");

                group_table.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null},
                                {null, null},
                                {null, null},
                                {null, null},
                                {null, null},
                                {null, null},
                                {null, null},
                                {null, null},
                                {null, null},
                                {null, null}
                        },
                        new String [] {
                                "own group", "other group"
                        }
                ) {
                        boolean[] canEdit = new boolean [] {
                                false, false
                        };

                        public boolean isCellEditable(int rowIndex, int columnIndex) {
                                return canEdit [columnIndex];
                        }
                });
                jScrollPane2.setViewportView(group_table);

                group_back.setText("back");
                group_back.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                group_backActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout groupLayout = new javax.swing.GroupLayout(group);
                group.setLayout(groupLayout);
                groupLayout.setHorizontalGroup(
                        groupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(groupLayout.createSequentialGroup()
                                .addGroup(groupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(groupLayout.createSequentialGroup()
                                                .addGap(438, 438, 438)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(groupLayout.createSequentialGroup()
                                                .addGap(626, 626, 626)
                                                .addComponent(group_back)))
                                .addContainerGap(709, Short.MAX_VALUE))
                );
                groupLayout.setVerticalGroup(
                        groupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, groupLayout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(group_back)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(237, 237, 237))
                );

                getContentPane().add(group, "card7");

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		retry =true;
        }//GEN-LAST:event_jButton1ActionPerformed

        private void passwdInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwdInputActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_passwdInputActionPerformed

        private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
		String login = loginInput.getText();
		char[] str = passwdInput.getPassword();
		String passwd ="";
		for (char c : str) {
			passwd +=c;
		}

		client.sendRequest(RequestName.IDENTIFICATION, login, passwd);
        }//GEN-LAST:event_jButton2ActionPerformed

        private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
		newUser.setVisible(true);
		identification.setVisible(false);
        }//GEN-LAST:event_jButton3ActionPerformed

        private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
                // TODO add your handling code here:
		String login = inputName.getText();
		char[] str = passwdInput.getPassword();
		String passwd ="";
		for (char c : str) {
			passwd +=c;
		}
		String firstName = newUser_firstName.getText();
		String name =newUser_name.getText();
		String status = inputStatus.getSelectedItem().toString();
		client.sendRequest(RequestName.NEW_USER, login, passwd, firstName, name, status);

        }//GEN-LAST:event_jButton4ActionPerformed

        private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
		identification.setVisible(true);
		newUser.setVisible(false);
        }//GEN-LAST:event_jButton5ActionPerformed

        private void home_groupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_groupActionPerformed
		group.setVisible(true);
		home.setVisible(false);

		client.sendRequest(RequestName.ALL_GROUP, (Object)null);
        }//GEN-LAST:event_home_groupActionPerformed

        private void group_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_group_backActionPerformed
		home.setVisible(true);
		group.setVisible(false);
        }//GEN-LAST:event_group_backActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(InterfaceClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(InterfaceClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(InterfaceClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(InterfaceClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>

		/* Create and display the form */
//		java.awt.EventQueue.invokeLater(new Runnable() {
//			public void run() {
//				new Interface().setVisible(true);
//			}
//		});

		InterfaceClient ihm = new InterfaceClient();
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JPanel group;
        private javax.swing.JButton group_back;
        private javax.swing.JTable group_table;
        private javax.swing.JPanel home;
        private javax.swing.JButton home_group;
        private javax.swing.JLabel home_userName;
        private javax.swing.JLabel home_wrong;
        private javax.swing.JPanel identification;
        private javax.swing.JTextField inputName;
        private javax.swing.JPasswordField inputPasswd;
        private javax.swing.JComboBox<String> inputStatus;
        private javax.swing.JButton jButton1;
        private javax.swing.JButton jButton2;
        private javax.swing.JButton jButton3;
        private javax.swing.JButton jButton4;
        private javax.swing.JButton jButton5;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel12;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JPanel jPanel4;
        private javax.swing.JPanel jPanel5;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JTextField loginInput;
        private javax.swing.JPanel newUser;
        private javax.swing.JTextField newUser_firstName;
        private javax.swing.JTextField newUser_name;
        private javax.swing.JPasswordField passwdInput;
        private javax.swing.JPanel serverConnect;
        private javax.swing.JPanel serverNotFound;
        private javax.swing.JTree tree;
        // End of variables declaration//GEN-END:variables

	private JPanel allPanel[] ={home, identification, newUser, serverConnect, serverNotFound};

	void display(JPanel panel) {
		for (JPanel p : allPanel) {
			if (p != null)
				p.setVisible(false);
		}
		panel.setVisible(true);
		this.revalidate();
	}

	// getters
	public JPanel getHome() {
		return home;
	}

	public JLabel getHome_userName() {
		return home_userName;
	}

	public JLabel getHome_wrong() {
		return home_wrong;
	}

	public JPanel getIdentification() {
		return identification;
	}

	void majTree() {
		DefaultMutableTreeNode root = new DefaultMutableTreeNode("posts");
		for (String g : client.getGroups()) {
			DefaultMutableTreeNode group = new DefaultMutableTreeNode(g);
			root.add(group);
		}

		tree = new JTree(root);

                jScrollPane1.setViewportView(tree);
//		jScrollPane1.removeAll();
//		jScrollPane1.add(tree)
//		jScrollPane1.revalidate();
	}

	public JTable getGroup_table() {
		return group_table;
	}

	void majGroupTable(Set<String> myGroup, Set<String> other) {
		Object data[][] =new Object[myGroup.size()][2];
		int i =0;
		for (String str : myGroup) {
			data[i][0] =str;
		}
		i =0;
		for (String str : other) {
			data[i][0] =str;
		}
		String title[] ={"myGroup", "otherGroup"};
		group_table =new JTable(data, title);

                jScrollPane2.setViewportView(group_table);
	}
	

	
	
}
